# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 500 # Hz

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    L_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    R_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
gripper_controller:
  ros__parameters:
    joints:
      - r_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

L_leg_controller:
  ros__parameters:
    joints:
      - coxa_LF_joint
      - femur_LF_joint
      - tibla_LF_joint
      - coxa_LM_joint
      - femur_LM_joint
      - tibla_LM_joint
      - coxa_LR_joint
      - femur_LR_joint
      - tibla_LR_joint

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

R_leg_controller:
  ros__parameters:
    joints:
      - coxa_RF_joint
      - femur_RF_joint
      - tibla_RF_joint
      - coxa_RM_joint
      - femur_RM_joint
      - tibla_RM_joint
      - coxa_RR_joint
      - femur_RR_joint
      - tibla_RR_joint

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
